images:
  - eu.gcr.io/ingenerator-ci/php-packages-ingen-builder:$BUILD_ID
tags:
  - "php-packages-ingenerator-com"
  - "$COMMIT_SHA"
timeout: 420s
steps:
  - id: 'fetch:composer-cache'
    name: gcr.io/cloud-builders/gsutil
    args: ['-m', '-q', 'cp', '-r', 'gs://ingenerator-composer-cache/php-packages-ingenerator-com/cache', '/tmp']
    volumes:
      - name: 'composer-cache'
        path: '/tmp'

  - id: 'build:composer'
    name: 'composer'
    args: ['install']
    volumes:
      - name: 'composer-cache'
        path: '/tmp'

  - id: 'build:docker'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'eu.gcr.io/ingenerator-ci/php-packages-ingen-builder:$BUILD_ID'
      - .

  - id: 'push:composer-cache'
    waitFor: ['build:composer']
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', '-q', 'cp', '-r', '-n', '/tmp/cache/files/', 'gs://ingenerator-composer-cache/php-packages-ingenerator-com/cache']
    volumes:
      - name: 'composer-cache'
        path: '/tmp'
