images:
  - eu.gcr.io/ingenerator-ci/php-packages-ingen-builder:$BUILD_ID
tags:
  - "php-packages-ingenerator-com"
  - "$COMMIT_SHA"
timeout: 420s
steps:
  - id: 'build:composer'
    name: 'gcr.io/ingenerator-ci/cached-composer-installer:0.1.x'
    env:
      - 'GCS_CACHE_BUCKET=ingen-us-composer-cache'
      - 'GCS_CACHE_BUCKET_PATH=ingenerator/php-packages.ingenerator.com'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'COMMIT_SHA=$COMMIT_SHA'

  - id: 'build:docker'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'eu.gcr.io/ingenerator-ci/php-packages-ingen-builder:$BUILD_ID'
      - .
